-- Finance data now syncs through public.finance_kv (one row per stored key),
-- created by macros/supabase/accounts-01-usernames-and-sync.sql, which also
-- sets up the shared Box of Jelly accounts. Both apps use the same Supabase project.
